import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				{children}
				<div className="hidden place-content-center bg-zinc-950 text-white text-xl absolute inset-0 z-50 sm:grid">
					<p className="text-balance text-center">
						Please view in mobile view, Desktop/Tablet view is not supported
						yet.
					</p>
				</div>
			</body>
		</html>
	)
}
